# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: build
on:
  push:
    branches: [master]
  pull_request:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.diff.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build matrix of changes paths
        id: diff
        run: |
          if [ "${{ github.base_ref }}" ]; then
            source=${{ github.base_ref }}
          else
            source=${{ github.event.before }}
          fi
          echo "source: ${source}"
          git fetch origin ${source} --depth=1
          changes=$(git diff --name-only -z ${source} ${GITHUB_SHA} | xargs -0 -n 1 find -L . -samefile | sed 's|^\./||')
          echo files changed:
          echo "${changes}"
          case "${changes}" in
            .*) images=$(find * -mindepth 1 -maxdepth 1 | sort -u)              ;; # dotfile changes rebuild all images
             *) images=$(echo "${changes}" | grep / | cut -d/ -f 1-2 | sort -u) ;; # otherwise build affected images
          esac
          echo images affected:
          echo "${images}"
          json=$(echo "${images}" | jq -R . | jq -s -c .)
          echo "json: ${json}"
          echo "::set-output name=images::${json}"
  image:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          annotate: true
          dockerfile: "${{ matrix.image }}/Dockerfile"
          error_level: 2
          output_format: tty
      - name: Generate tag
        id: tag
        run: |
          tag=epiphytelabs/$(echo "${{ matrix.image }}" | tr / :)
          echo "tag: ${tag}"
          echo "::set-output name=tag::${tag}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
