name: build
on: [push, pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.diff.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build matrix of changes paths
        id: diff
        run: |
          if [ $GITHUB_BASE_REF ]; then
            source=${GITHUB_BASE_REF}
          else
            source=${{ github.event.before }}
          fi
          git fetch origin ${source} --depth=1
          diff=$(git diff --name-only -z ${source} ${GITHUB_SHA} | xargs -0 -n 1 find -L * -samefile)
          echo files changed:
          echo "${diff}"
          echo "::set-output name=matrix::$(echo "${diff}\n${symlinks}" | grep -v .github | grep / | cut -d/ -f 1-2 | sort -u | jq -R . | jq -s -c .)"
  build:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        path: ${{ fromJSON(needs.changes.outputs.matrix) }}
    env:
      TAG:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate tag
        id: tag
        run: echo "::set-output name=tag::epiphytelabs/$(echo '${{ matrix.path }}' | sed -e 's|/|:|')"
      - name: Build
        run: echo building ${{ matrix.path }} as ${{ steps.tag.outputs.tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.path }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
